#!/bin/sh

if [ "${5:-}" = "192.168.3.10" ]
then
    export PATH="/sbin:/usr/sbin:/usr/bin"
    route delete 192.168.3.0/20

    #networksetup -setdnsservers Wi-Fi empty
    networksetup -setautoproxystate "Aijihui" off
    dscacheutil -flushcache

fi
